"use client";

export interface TranslationContent {
  [key: string]: string | string[] | TranslationContent;
}

export interface Translations {
  [key: string]: TranslationContent;
}

export const TRANSLATIONS: Translations = {
  ge: {
    // Navigation
    navigation: {
      home: "მთავარი",
      homePage: "მთავარი გვერდი",
      shop: "პროდუქტები",
      popular: "პოპულარული პროდუქტები",
      discounted: "ფასდაკლებული პროდუქტები",
      auction: "აუქციონი",
      myOrders: "ჩემი შეკვეთები",
      forum: "ფორუმი",
      about: "ჩვენს შესახებ",
      contact: "კონტაქტი",
      login: "ავტორიზაცია",
      profile: "პროფილი",
      addresses: "მისამართები",
      orders: "შეკვეთები",
      adminPanel: "ადმინ პანელი",
      products: "პროდუქტები",
      users: "მომხმარებლები",
      logout: "გასვლა",
    }, // Shop
    shop: {
      searchResults: "ძებნის შედეგები",
      backToHome: "მთავარ გვერდზე დაბრუნება",
      noResultsMessage: "პროდუქტები არ მოიძებნა თქვენი ძებნის კრიტერიუმებით",
      tryDifferent: " სცადეთ სხვა საკვანძო სიტყვა",
      noResults: "პროდუქტები არ მოიძებნა",
      browseAll: "ყველა პროდუქტის დათვალიერება",
      errorTitle: "შეცდომა",
      errorMessage:
        "პროდუქტების ჩატვირთვა ვერ მოხერხდა. გთხოვთ, სცადოთ მოგვიანებით.",
      allartworks: "ყველა პროდუქტი",
      artistWorks: "-ის პროდუქტები",
      loading: "იტვირთება...",
      filters: "ფილტრები",
      sort: "დალაგება",
      categories: "კატეგორიები",
      painters: "მხატვრები",
      priceRange: "ფასის დიაპაზონი",
      inStock: "მარაგშია",
      outOfStock: "არ არის მარაგში",
      mainCategory: "ძირითადი კატეგორია",
      searchPainter: "მოძებნე მხატვარი",
      authorCompany: "ავტორი/კომპანია",
      searchAuthorCompany: "მოძებნე ავტორი/კომპანია",
      defaultSort: "ნაგულისხმევი",
      priceLowToHigh: "ფასი: დაბლიდან მაღლისკენ",
      priceHighToLow: "ფასი: მაღლიდან დაბლისკენ",
      emptyDescription:
        "დაათვალიერეთ ჩვენი პლატფორმა და იპოვეთ უნიკალური პროდუქტები",
      seeAll: "ნახე ყველა",
      allAges: "ყველა ასაკი",
      adults: "მოზრდილები",
      kids: "ბავშვები",
      ageGroup: "ასაკობრივი ჯგუფი",
      newest: "უახლესი",
      // Filter-specific translations
      clear: "გასუფთავება",
      noCategories: "კატეგორიები არ მოიძებნა",
      ageGroupFilter: "ასაკობრივი ჯგუფი",
      sizes: "ზომები",
      colors: "ფერები",
      brands: "ბრენდები",
      sortBy: "სორტირება",
      min: "მინ",
      max: "მაქს",
      applyPrice: "დადასტურება",
      priceLowHigh: "ფასი: დაბლიდან მაღლა",
      priceHighLow: "ფასი: მაღლიდან დაბლა",
      nameAZ: "სახელი: ა-ჰ",
      nameZA: "სახელი: ჰ-ა",
      ratingHigh: "რეიტინგი: მაღალი",
      clearAllFilters: "ფილტრების გასუფთავება",
      filterToggle: "ფილტრი",
      close: "დახურვა",
      // Error messages
      errorLoadingCategories: "კატეგორიების ჩატვირთვა ვერ მოხერხდა",
      errorLoadingSubcategories: "ქვეკატეგორიების ჩატვირთვა ვერ მოხერხდა",
      // New translations
      subcategories: "ქვეკატეგორიები",
      apply: "გამოყენება",
      searchBrands: "ძებნა ბრენდებში",
      noBrandsFound: "ბრენდი ვერ მოიძებნა",
      showDiscountedProducts: "მხოლოდ ფასდაკლებული პროდუქტები",
      resetFilters: "ფილტრების განულება",
    }, // Product Details
    product: {
      ref: "Ref:",
      reviews: "შეფასებები",
      dimensions: "პროდუქტის ზომები",
      deliveryTime: "მიწოდების ვადა",
      days: "დღე",
      tryInRoom: "მოარგე ოთახს",
      quantity: "რაოდენობა",
      details: "აღწერა",
      author: "ავტორი",
      similarProducts: "მსგავსი პროდუქტები",
      selectAgeGroup: " ასაკი",
      selectSize: "ზომა",
      selectColor: "ფერი",
      addToCartSuccess: "პროდუქტი წარმატებით დაემატა კალათაში!",
      addToCartError: "პროდუქტის კალათაში დამატება ვერ მოხერხდა",
      errorTitle: "შეცდომა",
    },

    // Room Viewer
    roomViewer: {
      title: "მოარგე ოთახს",
      chooseRoom: "აირჩიე ოთახი",
      livingRoom: "მისაღები",
      bedroom: "საძინებელი",
      kitchen: "სამზარეულო",
      hall: "დერეფანი",
      artworkSize: "პროდუქტის ზომა",
      wallColor: "კედლის ფერი",
      instructions:
        "გადაიტანეთ არჩეული პროდუქტი კედელზე სასურველ პოზიციაზე. გამოიყენეთ ზომის რეგულატორი.",
      loading: "ოთახის სურათების ჩატვირთვა...",
      artworkLoading: "პროდუქტების ჩატვირთვა...",
    },

    // Profile
    profile: {
      title: "მომხმარებლის პროფილი",
      uploadAvatar: "პროფილის სურათის ატვირთვა",
      uploading: "იტვირთება...",
      uploadSuccess: "სურათი წარმატებით აიტვირთა",
      name: "სახელი",
      email: "ელ-ფოსტა",
      newPassword: "ახალი პაროლი",
      confirmPassword: "გაიმეორეთ ახალი პაროლი",
      passwordPlaceholder: "დატოვეთ ცარიელი არსებული პაროლის შესანარჩუნებლად",
      updateProfile: "პროფილის განახლება",
      updating: "მიმდინარეობს განახლება...",
      updateSuccess: "🎉 პროფილი წარმატებით განახლდა!",
      loading: "იტვირთება...",
      updateError: "განახლება ვერ მოხერხდა",
      updateErrorDescription:
        "პროფილის განახლება ვერ მოხერხდა. გთხოვთ, სცადოთ მოგვიანებით.",
      uploadError: "ატვირთვა ვერ მოხერხდა",
      uploadErrorDescription:
        "სურათის ატვირთვა ვერ მოხერხდა. გთხოვთ, სცადოთ მოგვიანებით.",
      passwordChanged: "პაროლი შეიცვალა",
      passwordChangedDescription: "თქვენი პაროლი წარმატებით შეიცვალა.",
      updateSuccessDescription: "თქვენი პროფილი წარმატებით განახლდა.",
    },

    // Cart & Checkout
    cart: {
      yourCart: "თქვენი კალათა",
      items: "ნივთი",
      empty: "თქვენი კალათა ცარიელია",
      total: "ჯამი",
      viewCart: "ნახე კალათა",
      delivery: "მიწოდება",
      free: "უფასო",
      commission: "საკომისიო",
      totalCost: "სრული ღირებულება",
      checkout: "შეკვეთის გაფორმება",
      remove: "წაშლა",
      addToCart: "კალათაში დამატება",
      adding: "ემატება...",
      outOfStock: "არ არის მარაგში",
      title: "კალათა",
      emptyDescription:
        "თქვენი კალათა ცარიელია. დაამატეთ პროდუქტები, რომ დაიწყოთ შოპინგი.",
      size: "ზომა",
      color: "ფერი",
      age: "ასაკი",
    },

    // Checkout
    checkout: {
      // Steps
      authenticationStep: "ავტორიზაცია",
      shippingStep: "მიწოდება",
      orderStep: "შეკვეთა",
      // Forms
      shippingAddress: "მიწოდების მისამართი",
      enterShippingDetails: "შეავსეთ მიწოდების დეტალები",
      streetAddress: "ქუჩის მისამართი",
      addressPlaceholder: "მაგ: რუსთაველის გამზ. 123",
      addressRequired: "მისამართი აუცილებელია",
      city: "ქალაქი",
      cityPlaceholder: "თბილისი",
      cityRequired: "ქალაქი აუცილებელია",
      postalCode: "საფოსტო კოდი",
      postalCodePlaceholder: "0100",
      postalCodeRequired: "საფოსტო კოდი აუცილებელია",
      phoneNumber: "ტელეფონის ნომერი",
      phoneNumberPlaceholder: "+995 555 123 456",
      phoneNumberRequired: "ტელეფონის ნომერი აუცილებელია",
      validPhoneNumber: "გთხოვთ შეიყვანოთ სწორი ტელეფონის ნომერი",
      country: "ქვეყანა",
      selectCountry: "აირჩიეთ ქვეყანა",
      countryRequired: "ქვეყანა აუცილებელია",
      continueToPayment: "გადასვლა გადახდაზე",
      errorSavingShipping: "შეცდომა მიწოდების დეტალების შენახვისას",
      pleaseTryAgain: "გთხოვთ სცადოთ თავიდან.",
      duplicateOrder: "შეკვეთა უკვე გაიგზავნა",
      duplicateOrderDescription:
        "გთხოვთ დაელოდოთ ან შეამოწმოთ თქვენი შეკვეთები",
      paymentMethod: "გადახდის მეთოდი",
      choosePaymentMethod: "აირჩიეთ როგორ გსურთ გადახდა",
      cardPayment: "ბარათით გადახდა",
      continueToReview: "გადასვლა შემოწმებაზე",
      errorSavingPayment: "შეცდომა გადახდის მეთოდის შენახვისას",
      shipping: "მიწოდება",
      address: "მისამართი",
      phone: "ტელეფონი",
      payment: "გადახდა",
      method: "მეთოდი",
      orderItems: "შეკვეთის ნივთები",
      orderSummary: "შეკვეთის შეჯამება",
      items: "ნივთები",
      shippingCost: "მიწოდება",
      free: "უფასო",
      tax: "დღგ",
      total: "ჯამი",
      placeOrder: "შეკვეთის დადასტურება",
      placingOrder: "იტვირთება...",
      errorPlacingOrder: "შეცდომა შეკვეთის განთავსებისას",
    },

    // Order Details
    order: {
      order: "შეკვეთა",
      paid: "გადახდილი",
      pendingPayment: "გადახდის მოლოდინში",
      cancelled: "გაუქმებული",
      shipping: "მიწოდება",
      address: "მისამართი",
      phone: "ტელეფონი",
      deliveredOn: "მიტანილია",
      notDelivered: "არ არის მიტანილი",
      payment: "გადახდა",
      method: "მეთოდი",
      paidOn: "გადახდილია",
      notPaid: "არ არის გადახდილი",
      orderItems: "შეკვეთის ნივთები",
      sellerDelivery: "გამყიდველის მიწოდება",
      deliveryTime: "მიწოდების დრო",
      days: "დღე",
      orderSummary: "შეკვეთის შეჯამება",
      items: "ნივთები",
      shippingCost: "მიწოდება",
      free: "უფასო",
      tax: "დღგ",
      total: "ჯამი",
      totalUSD: "ჯამი (USD)",
      stockExpired:
        "მარაგის რეზერვაცია ამოიწურა. გთხოვთ შექმნათ ახალი შეკვეთა.",
      orderCancelled: "შეკვეთა გაუქმდა",
      stockReservedUntil: "მარაგი დაჯავშნულია",
      paymentButton: "გადახდა",
      processing: "მუშავდება...",
    },

    // About page
    about: {
      title: "ჩვენს შესახებ",
      description:
        "13 არის პლატფორმა, რომელიც აერთიანებს მხატვრებს და ხელოვნების მოყვარულებს. ჩვენი მიზანია შევქმნათ სივრცე ხელოვნებისთვის.",
      goal: {
        title: "მიზანი",
        description:
          "ჩვენი მიზანია გავაერთიანოთ ხელოვნების მოყვარულები და მხატვრები ერთიან სივრცეში, სადაც ხელოვნება ყველასთვის ხელმისაწვდომი იქნება.",
      },
      vision: {
        title: "ხედვა",
        description:
          "ცამეტი არის მამაკაცების კლასიკური ტანსაცმლის მაღაზია საქართველოში. ჩვენი ხედვაა გავხდეთ მამაკაცების სტილის მთავარი ადგილი.",
      },
      whyUs: {
        title: "რატომ ცამეტი?",
        description:
          "საქართველოში მსგავსი პლატფორმა არ არსებობს. ჩვენ ვქმნით უნიკალურ შესაძლებლობას, სადაც ხელოვნება და ტექნოლოგია ერთმანეთს ხვდება.",
      },
      buyUnique: {
        title: "შეიძინეთ უნიკალური პროდუქტები",
        description:
          "ეძებთ უნიკალურ ხელოვნების ნიმუშებს? დაათვალიერეთ ჩვენი პლატფორმა და იპოვეთ პროდუქტები, რომლებიც თქვენს გემოვნებას შეესაბამება.",
        button: "დაათვალიერეთ პროდუქტები",
      },
    },

    // Seller benefits
    sellerBenefits: {
      title: "შექმენი შენი პირადი ონლაინ მაღაზია ცამეტიზე",
      subtitle:
        "13.online.ge — მამაკაცების კლასიკური ტანსაცმლის პლატფორმა, სადაც შეგიძლიათ შექმნათ უნიკალური ონლაინ მაღაზია და გაყიდოთ თქვენი პროდუქტები მარტივად და კომფორტულად. გახსენით ახალი შესაძლებლობები თქვენი პროდუქტებისთვის!",
      benefits: {
        title: "🌟 უპირატესობები ხელოვანებისთვის",
        items: [
          "სრულიად უფასო პირადი ონლაინ გალერეა ულიმიტო პროდუქტებით",
          "მარტივი რეგისტრაცია და პროდუქტების ატვირთვა",
          "პირველი თვე - 0% საკომისიო გაყიდვებზე",
          "შემდგომი პერიოდი - მხოლოდ 10% წარმატებული გაყიდვებიდან",
          "ანაზღაურების მომენტალური ჩარიცხვა მითითებულ ანგარიშზე, მას შემდეგ რაც მომხმარებელი დაადასტურებს რომ მიიღო შეკვეთა",
          "დეტალური სტატისტიკა და სრული კონტროლი თქვენს გაყიდვებზე",
          "თქვენი პროდუქტების პოპულარიზაცია ფართო აუდიტორიაში",
        ],
      },
      shipping: {
        title: "🚚 მოქნილი მიწოდების პირობები",
        items: [
          "მიწოდების ტიპს თავად ირჩევთ პროდუქტის ატვირთვისას",
          "პირადი მიწოდების შემთხვევაში - დამატებითი გადასახადი არ არის",
          "ცამეტის კურიერის სერვისით სარგებლობისას დაემატება მხოლოდ 4% ლოჯისტიკური საკომისიო",
          "მიწოდების ვარიანტები ავტომატურად ჩანს თქვენს პანელში და მარტივად იმართება",
          "უსაფრთხო ტრანზაქციები და მყიდველებთან კომუნიკაცია პლატფორმის შიგნით",
        ],
      },
      cta: {
        text: "✨ დაიწყეთ მოგზაურობა ცამეტიზე და მიეცით თქვენს პროდუქტებს ის აუდიტორია, რომელსაც იმსახურებენ!",
        button: "დარეგისტრირდი ახლავე",
      },
    },

    // Footer
    footer: {
      copyright: "CREATED BY",
      description:
        "აღმოაჩინეთ ჩვენი სახალისო კოლექცია მაისურების, ჩანთების და აქსესუარების გულის დიზაინით, რომლებიც დაჭერისას სასაცილო 'პიპ' ხმას გამოსცემენ. შეიტანეთ მხიარულება და სიურპრიზი თქვენს ყოველდღიურ სტილში!",
      quickLinks: "სწრაფი ბმულები",
      termsOfService: "მომსახურების პირობები",
      privacyPolicy: "კონფიდენციალურობის პოლიტიკა",
      contact: "კონტაქტი",
      address: "მისამართი: თბილისი, საქართველო",
      email: "ელ-ფოსტა: kakhaber.shop13@gmail.com",
      phone: "ტელეფონი: +995 574150531",
      socialMedia: "სოციალური ქსელები",
      follow: "მოგვყევით",
      newsletter: "სიახლეების გამოწერა",
      subscribePrompt: "გამოიწერეთ სიახლეები და მიიღეთ განახლებები",
      subscribe: "გამოწერა",
      emailPlaceholder: "შეიყვანეთ თქვენი ელფოსტა",
      beforeYouLeave: "სანამ წახვალ დააპიპინეეე!!!",
      privacy: "კონფიდენციალურობა",
      terms: "წესები და პირობები",
      returnPolicy: "დაბრუნების წესები",
    },
    home: {
      heroTitle: "შეარჩიე ხელოვანების პროდუქტები ან გაყიდე შენი 🖌️",
      heroSubtitle:
        "პერსონალური და ხელნაკეთი პროდუქტები ქართველი ხელოვანებისგან",
      mostPopular: "ყველაზე პოპულარული",
      welcomeMessage: "მოგესალმებით საპიპინეთშიიიიიიიი !!!",
      pipSound: "პიიიპ პიიიიპ!",
    },

    // Timer translations
    timer: {
      loading: "იტვირთება...",
      message: "საიტის დასრულებამდე დარჩა",
      day: "დღე",
      days: "დღე",
      hour: "საათი",
      hours: "საათი",
      minute: "წუთი",
      minutes: "წუთი",
      second: "წამი",
      seconds: "წამი",
      month: "თვე",
    },

    // Common action buttons
    actions: {
      save: "შენახვა",
      cancel: "გაუქმება",
      edit: "რედაქტირება",
      delete: "წაშლა",
      send: "გაგზავნა",
      create: "შექმნა",
      close: "დახურვა",
      add: "დამატება",
      back: "უკან",
      next: "შემდეგი",
      submit: "გაგზავნა",
    },

    // Language selector
    language: {
      en: "ENG",
      ge: "ქარ",
    },
    auth: {
      login: "ავტორიზაცია",
      register: "რეგისტრაცია",
      name: "სახელი",
      email: "ელ-ფოსტა",
      password: "პაროლი",
      confirmPassword: "გაიმეორეთ პაროლი",
      rememberMe: "დამიმახსოვრე",
      forgotPassword: "დაგავიწყდათ პაროლი?",
      fullName: "სრული სახელი",
      loginButton: "ავტორიზაცია",
      registerButton: "რეგისტრაცია",
      alreadyHaveAccount: "უკვე გაქვთ ანგარიში?",
      dontHaveAccount: "არ გაქვთ ანგარიში?",
      createAccount: "შექმენით ანგარიში",
      loginWelcome: "შედით თქვენი ანგარიშით",
      loginSubtitle: "კეთილი იყოს თქვენი დაბრუნება!",
      registerWelcome: "მოგესალებით ჩვენს სამყაროში!",
      registerSubtitle: "გთხოვთ, შეავსოთ რეგისტრაციის ფორმა",
      requiredField: "სავალდებულო ველი",
      invalidEmail: "არასწორი ელ-ფოსტის ფორმატი",
      passwordTooShort: "პაროლი უნდა შეიცავდეს მინიმუმ 6 სიმბოლოს",
      passwordsDontMatch: "პაროლები არ ემთხვევა",
      termsAgreement: "ვეთანხმები მომსახურების პირობებს",
      personalInfo: "პირადი ინფორმაცია",
      firstName: "სახელი",
      lastName: "გვარი",
      phoneNumber: "ტელეფონის ნომერი",
      emailRequired: "ელ-ფოსტის მითითება აუცილებელია",
      enterNewPassword: "შეიყვანეთ ახალი პაროლი",
      confirmNewPassword: "დაადასტურეთ ახალი პაროლი",
      registrationSuccessful: "რეგისტრაცია წარმატებულია",
      accountCreatedSuccessfully: "ანგარიში წარმატებით შეიქმნა",
      redirectingToLogin: "მიმდინარეობს გადამისამართება ავტორიზაციის გვერდზე",
      loginSuccess: "წარმატებით შეხვედით",
      loginFailed: "ავტორიზაცია ვერ მოხერხდა",
      invalidCredentials: "არასწორი მეილი ან პაროლი",
      registrationFailed: "რეგისტრაცია ვერ მოხერხდა",
      emailAlreadyExists: "ეს ელ-ფოსტა უკვე რეგისტრირებულია",
      invalidData:
        "მონაცემები არასწორია. გთხოვთ, შეამოწმოთ შეყვანილი ინფორმაცია.",
      orContinueWith: "ან გააგრძელეთ",
      forgotPasswordTitle: "განაახლეთ პაროლი",
      forgotPasswordSubtitle: "გთხოვთ, შეავსოთ პაროლის აღდგენის ფორმა",
      welcomeBack: "კეთილი იყოს თქვენი დაბრუნება!",
      // Validation error messages
      nameRequired: "სახელის მითითება აუცილებელია",
      nameTooShort: "სახელი უნდა შეიცავდეს მინიმუმ 3 სიმბოლოს",
      nameInvalid: "არასწორი სახელი",
      emailInvalid: "არასწორი ელ-ფოსტის ფორმატი",
      passwordRequired: "პაროლის მითითება აუცილებელია",
      passwordMinLength: "პაროლი უნდა შეიცავდეს მინიმუმ 6 სიმბოლოს",
      agreeToPrivacyPolicy: "ვეთანხმები ",
      privacyPolicy: "კონფიდენციალურობას",
      privacyPolicyRequired:
        "კონფიდენციალურობის პოლიტიკაზე თანხმობა აუცილებელია",
      agreeToTermsAndConditions: "ვეთანხმები ",
      termsAndConditions: "წესებს",
      agreeToReturnPolicy: "ვეთანხმები ",
      returnPolicy: "დაბრუნების წესებს",
      // Forgot/Reset password
      success: "წარმატება",
      error: "შეცდომა",
      checkEmailForResetLink:
        "შეამოწმეთ თქვენი ელ-ფოსტა პაროლის აღდგენის ბმულისთვის",
      somethingWentWrong: "რაღაც არასწორად მოხდა",
      enterYourEmail: "შეიყვანეთ თქვენი ელ-ფოსტა",
      sending: "იგზავნება...",
      sendResetLink: "აღდგენის ბმულის გაგზავნა",
      invalidResetLink: "არასწორი აღდგენის ბმული",
      passwordResetSuccessful: "პაროლი წარმატებით შეიცვალა",
      passwordUpdated: "თქვენი პაროლი განახლდა",
      passwordResetFailed: "პაროლის შეცვლა ვერ მოხერხდა",
      newPassword: "ახალი პაროლი",
      updatingPassword: "პაროლი განახლდება...",
      resetPassword: "პაროლის შეცვლა",
      authenticationRequired: "ავტორიზაცია საჭიროა",
      pleaseLogin: "გთხოვთ ჯერ შეხვიდეთ სისტემაში",
    },

    // Contact form
    contact: {
      title: "კონტაქტი",
      description:
        "თუ გაქვთ შეკითხვები ან გსურთ ჩვენთან დაკავშირება, გთხოვთ შეავსოთ ქვემოთ მოცემული ფორმა.",
      name: "სახელი",
      email: "ელ-ფოსტა",
      subject: "თემა",
      message: "მესიჯი",
      send: "გაგზავნა",
      sending: "იგზავნება...",
      nameRequired: "სახელის შეყვანა აუცილებელია",
      emailRequired: "ელ-ფოსტის შეყვანა აუცილებელია",
      subjectRequired: "თემის შეყვანა აუცილებელია",
      messageRequired: "მესიჯის შეყვანა აუცილებელია",
      namePlaceholder: "შეიყვანეთ თქვენი სახელი",
      emailPlaceholder: "შეიყვანეთ თქვენი ელ-ფოსტა",
      subjectPlaceholder: "შეიყვანეთ თემა",
      messagePlaceholder: "შეიყვანეთ თქვენი შეტყობინება",
      successTitle: "შეტყობინება გაიგზავნა!",
      successMessage:
        "თქვენი შეტყობინება წარმატებით გაიგზავნა. მალე დაგიკავშირდებით!",
      sendAnother: "ახალი შეტყობინების გაგზავნა",
      sendError: "შეცდომა შეტყობინების გაგზავნისას. გთხოვთ სცადოთ თავიდან.",
    },

    // Art Categories
    categories: {
      // Main categories
      paintings: "ნახატები",
      handmade: "ხელნაკეთი ნივთები",
      clothing: "ტანსაცმელი",
      accessories: "აქსესუარები",
      footwear: "ფეხსაცმელი",
      swimwear: "საცურაო კოსტუმები",

      // Painting subcategories
      oil: "ზეთი",
      acrylic: "აკრილი",
      watercolor: "აკვარელი",
      pastel: "პასტელი",
      drawing: "ნახატი",
      mixedMedia: "შერეული მედია",
      abstract: "აბსტრაქცია",
      landscape: "პეიზაჟი",
      portrait: "პორტრეტი",
      stillLife: "ნატურმორტი",
      contemporary: "თანამედროვე",
      modern: "მოდერნი",
      impressionism: "იმპრესიონიზმი",
      expressionism: "ექსპრესიონიზმი",
      realism: "რეალიზმი",
      surrealism: "სიურეალიზმი",
      digital: "ციფრული",
      blackAndWhite: "შავ-თეთრი",
      animation: "ანიმაციური",
      digitalIllustrations: "ციფრული ილუსტრაციები",
      other: "სხვა",

      // Handmade subcategories
      pottery: "კერამიკა",
      woodwork: "ხის ნაკეთობები",
      jewelry: "სამკაულები",
      textile: "ტექსტილი",
      glasswork: "მინის ნაკეთობები",
      sculpture: "სკულპტურა",
      enamel: "მინანქარი",
      sculptures: "სკულპტურები",
      otherHandmade: "სხვა",

      // Clothing subcategories
      tshirts: "მაისურები",
      dresses: "კაბები",
      hoodies: "ჰუდები",

      // Accessories subcategories
      caps: "კეპები",
      hats: "პანამები",

      // Footwear subcategories
      sporty: "სპორტული",
      casual: "ყოველდღიური",

      // Swimwear subcategories
      swimsuits: "საცურაო კოსტუმები",
    },

    // Forum
    forum: {
      addNewPost: "➕ ახალი პოსტის დამატება",
      loadingMore: "იტვირთება მეტი...",
      addPostSeeOthers: "დაამატე პოსტი / ნახე სხვა პოსტებიც",
      edit: "რედაქტირება",
      delete: "წაშლა",
      save: "შენახვა",
      cancel: "გაუქმება",
      reply: "პასუხი",
      like: "მოწონება",
      unlike: "მოწონების გაუქმება",
      writeReply: "დაწერეთ პასუხი...",
      writeComment: "დაწერეთ კომენტარი...",
      posting: "იგზავნება...",
      send: "გაგზავნა",
      selectTag: "აირჩიეთ თეგი",
      creating: "იქმნება...",
      create: "შექმნა",
      newPost: "ახალი პოსტის შექმნა",
      writePostContent: "დაწერეთ პოსტის შინაარსი...",
      tags: {
        handmade: "ხელნაკეთი ნივთები",
        paintings: "ნახატები",
        other: "სხვა",
      },
    },

    // Categories translations
    productCategories: {
      // Painting subcategories
      პეიზაჟი: "პეიზაჟი",
      პორტრეტი: "პორტრეტი",
      აბსტრაქცია: "აბსტრაქცია",
      "შავ-თეთრი": "შავ-თეთრი",
      ანიმაციური: "ანიმაციური",
      "ციფრული ილუსტრაციები": "ციფრული ილუსტრაციები",
      მინიატურა: "მინიატურა",
      სხვა: "სხვა",

      // Handmade subcategories
      კერამიკა: "კერამიკა",
      "ხის ნაკეთობები": "ხის ნაკეთობები",
      სამკაულები: "სამკაულები",
      ტექსტილი: "ტექსტილი",
      მინანქარი: "მინანქარი",
      სკულპტურები: "სკულპტურები",

      // Clothing subcategories
      მაისურები: "მაისურები",
      კაბები: "კაბები",
      ჰუდები: "ჰუდები",

      // Accessories subcategories
      კეპები: "კეპები",
      პანამები: "პანამები",

      // Footwear subcategories
      სპორტული: "სპორტული",
      ყოველდღიური: "ყოველდღიური",

      // Swimwear subcategories
      "საცურაო კოსტუმები": "საცურაო კოსტუმები",
    }, // Admin Categories
    adminCategories: {
      title: "კატეგორიების მართვა",
      categories: "კატეგორიები",
      subcategories: "ქვეკატეგორიები",
      add: "დამატება",
      edit: "რედაქტირება",
      delete: "წაშლა",
      cancel: "გაუქმება",
      update: "განახლება",
      confirmDelete: "დარწმუნებული ხართ, რომ გსურთ წაშლა?",
      showInactive: "არააქტიურების ჩვენება",
      active: "აქტიური",
      inactive: "არააქტიური",
      nameGe: "დასახელება (ქართულად)",
      nameEn: "დასახელება (ინგლისურად)",
      descriptionGe: "აღწერა (ქართულად)",
      descriptionEn: "აღწერა (ინგლისურად)",
      addNewCategory: "ახალი კატეგორიის დამატება",
      addNewSubcategory: "ახალი ქვეკატეგორიის დამატება",
      noCategoriesFound: "კატეგორიები არ მოიძებნა",
      noSubcategoriesFound: "ქვეკატეგორიები არ მოიძებნა",
      loading: "იტვირთება",
      colors: "ფერები",
      sizes: "ზომები",
      ageGroups: "ასაკობრივი ჯგუფები",
      attributes: "ატრიბუტები",
      confirmDeleteCategory: "დარწმუნებული ხართ, რომ გსურთ კატეგორიის წაშლა?",
      confirmDeleteSubcategory:
        "დარწმუნებული ხართ, რომ გსურთ ქვეკატეგორიის წაშლა?",
      createError: "ქვეკატეგორიის შექმნა ვერ მოხერხდა",
      editValue: "რედაქტირება",
      newValue: "ახალი მნიშვნელობა",
      georgian: "ქართულად",
      english: "ინგლისურად",
      enterColor: "შეიყვანეთ ფერი...",
      enterSize: "შეიყვანეთ ზომა...",
      enterAgeGroup: "შეიყვანეთ ასაკობრივი ჯგუფი...",
      enterColorEnglish: "Enter color in English...",
      enterAgeGroupEnglish: "Enter age group in English...",
      noDataFound: "მონაცემები არ მოიძებნა",
      updateError: "ქვეკატეგორიის განახლება ვერ მოხერხდა",
      deleteError: "ქვეკატეგორიის წაშლა ვერ მოხერხდა",
      retry: "ხელახლა ცდა",
    },

    // Admin Orders
    adminOrders: {
      orderNumber: "შეკვეთა #{id}",
      paid: "გადახდილი",
      cancelled: "გაუქმებული",
      orderCancelled: "შეკვეთა გაუქმებულია. მიზეზი: {reason}",
      "Order has been cancelled": "შეკვეთა გაუქმებულია",
      pendingPayment: "გადახდის მოლოდინში",
      markAsDelivered: "მიწოდებულად მონიშვნა",
      shipping: "მიწოდება",
      customer: "მყიდველი",
      address: "მისამართი",
      deliveredOn: "მიწოდებულია {date}",
      notDelivered: "არ არის მიწოდებული",
      payment: "გადახდა",
      method: "მეთოდი",
      paidOn: "გადახდილია {date}",
      notPaid: "არ არის გადახდილი",
      orderItems: "შეკვეთის ნივთები",
      size: "ზომა",
      color: "ფერი",
      age: "ასაკი",
      deliveryTime: "მიწოდების ვადა",
      days: "დღე",
      orderSummary: "შეკვეთის შეჯამება",
      items: "ნივთები",
      tax: "გადასახადი",
      total: "სულ",
      sellerDelivery: "აგზავნის ავტორი",
      storeDelivery: "ცამეტის კურიერი",
      stockReservationExpired:
        "სტოქის რეზერვაცია ვადაგასულია. გთხოვთ, შექმნათ ახალი შეკვეთა.",
      stockReservedUntil: "სტოქი დარეზერვებულია:",
      print: "ამობეჭდვა",
      buyerName: "მყიდველის სახელი",
      buyerEmail: "ელ-ფოსტა",
      orderDate: "შეკვეთის თარიღი",
      phone: "ტელეფონი",
    },

    adminProducts: {
      products: "პროდუქტები",
      users: "მომხმარებლები",
      orders: "შეკვეთები",
      createUser: "მომხმარებლის შექმნა",
      editUser: "მომხმარებლის რედაქტირება",
      name: "სახელი",
      email: "ელ-ფოსტა",
      password: "პაროლი",
      role: "როლი",
      admin: "ადმინისტრატორი",
      seller: "გამყიდველი",
      customer: "მყიდველი",
      joined: "რეგისტრაცია",
      actions: "ქმედებები",
      id: "ID",
      user: "მომხმარებელი",
      date: "თარიღი",
      delivered: "მიწოდებული",
      details: "დეტალები",
      previous: "წინა",
      next: "შემდეგი",
      page: "გვერდი",
      of: "-დან",
      // Product form translations
      productName: "პროდუქტის სახელი",
      productNameGe: "პროდუქტის სახელი (ქართულად)",
      productNameEn: "პროდუქტის სახელი (ინგლისურად)",
      description: "აღწერა",
      descriptionGe: "აღწერა (ქართულად)",
      descriptionEn: "აღწერა (ინგლისურად)",
      price: "ფასი",
      category: "კატეგორია",
      subcategory: "ქვეკატეგორია",
      selectCategory: "აირჩიეთ კატეგორია",
      selectSubcategory: "აირჩიეთ ქვეკატეგორია",
      ageGroups: "ასაკობრივი ჯგუფები",
      sizes: "ზომები",
      colors: "ფერები",
      stock: "რაოდენობა მარაგში",
      brand: "ბრენდი",
      images: "პროდუქტის სურათები",
      brandLogo: "ბრენდის ლოგო (არასავალდებულო)",
      createProduct: "პროდუქტის დამატება",
      updateProduct: "პროდუქტის განახლება",
      productCreated: "პროდუქტი წარმატებით დაემატა!",
      productUpdated: "პროდუქტი წარმატებით განახლდა!",
      loading: "იტვირთება...",
      selectAtLeastOneImage: "გთხოვთ აირჩიოთ მინიმუმ ერთი სურათი",
      enterBrandName: "შეიყვანეთ ბრენდის სახელი",
      productNameEnPlaceholder: "Product name in English (optional)",
      descriptionEnPlaceholder: "Product description in English (optional)",
      // Error messages
      selectCategoryError: "გთხოვთ აირჩიოთ კატეგორია",
      selectSubcategoryError: "გთხოვთ აირჩიოთ ქვეკატეგორია",
      invalidImageFormat:
        "მხოლოდ JPG, JPEG და PNG ფორმატის სურათებია დაშვებული",
      noImageSelected: "მინიმუმ ერთი სურათი მაინც უნდა აიტვირთოს",
      deliveryDaysRequired:
        "გთხოვთ მიუთითოთ მიწოდების დრო თუ გამყიდველი ასრულებს მიწოდებას.",
      authError: "ავტორიზაცია ვერ მოხერხდა. გთხოვთ, შეხვიდეთ თავიდან.",
      createUpdateError: "პროდუქტის დამატება/განახლება ვერ მოხერხდა",
      generalError: "რაღაც შეცდომა მოხდა", // Success messages
      productAddedSuccess: "პროდუქტი წარმატებით დაემატა!",
      productUpdatedSuccess: "პროდუქტი წარმატებით განახლდა!",
      productCreatedToast: "პროდუქტი დაემატა",
      productUpdatedToast: "პროდუქტი განახლდა",
      successTitle: "წარმატებით!", // Buttons and actions
      removeImage: "✕",
      uploadReminder: "გთხოვთ აირჩიოთ მინიმუმ ერთი სურათი",
      fixErrorsBeforeSubmit: "გასწორეთ შეცდომები გაგზავნამდე",
      requiredFields: "სავალდებულო ველები",
      // Validation error messages
      productNameRequired: "პროდუქტის სახელი აუცილებელია",
      productNameInvalid: "პროდუქტის სახელი არასწორია",
      priceRequired: "ფასის მითითება აუცილებელია",
      priceInvalid: "ფასი უნდა იყოს დადებითი რიცხვი",
      descriptionRequired: "აღწერა აუცილებელია",
      descriptionInvalid: "აღწერა არასწორია,უნდა იყოს მინიმუმ 5 სიმბოლო",
      brandRequired: "ბრენდის მითითება აუცილებელია",
      brandInvalid: "ბრენდის სახელი არასწორია",
    },

    brand: {
      ourPartners: "ჩვენი პარტნიორები",
      brandSubtitle:
        "მაღალი ხარისხის ნადირობის აღჭურვილობა წამყვანი ბრენდებისგან",
    },
  },

  en: {
    // Navigation
    navigation: {
      home: "Home",
      homePage: "Home Page",
      shop: "Shop Products",
      popular: "Popular Products",
      discounted: "Discounted Products",
      auction: "Auction",
      myOrders: "My Orders",
      forum: "Forum",
      about: "About",
      contact: "Contact",
      login: "Login",
      profile: "Profile",
      addresses: "Addresses",
      orders: "Orders",
      adminPanel: "Admin Panel",
      products: "Products",
      users: "Users",
      logout: "Logout",
    }, // Shop
    shop: {
      searchResults: "Search Results",
      backToHome: "Back to Home",
      noResultsMessage: "No products found matching your search criteria",
      tryDifferent: "Try different keywords or filters",
      noResults: "No products found",
      browseAll: "Browse All Products",
      errorTitle: "Error",
      errorMessage: "Failed to load products. Please try again later.",
      allArtworks: "All Products",
      allCategories: "All Categories",
      loading: "Loading...",
      filters: "Filters",
      sort: "Sort",
      categories: "Categories",
      painters: "Artists",
      priceRange: "Price Range",
      inStock: "In Stock",
      outOfStock: "Out of Stock",
      mainCategory: "Main Category",
      searchPainter: "Search Artist",
      authorCompany: "Author/Company",
      searchAuthorCompany: "Search author/company",
      defaultSort: "Default",
      priceLowToHigh: "Price: Low to High",
      priceHighToLow: "Price: High to Low",
      emptyDescription: "Browse our platform to find unique products",
      seeAll: "See All",
      allAges: "All Ages",
      adults: "Adults",
      kids: "Kids",
      ageGroup: "Age Group",
      newest: "Latest",
      // Filter-specific translations
      clear: "Clear",
      noCategories: "No categories found",
      ageGroupFilter: "Age Group",
      sizes: "Sizes",
      colors: "Colors",
      brands: "Brands",
      sortBy: "Sort By",
      min: "Min",
      max: "Max",
      applyPrice: "Apply",
      priceLowHigh: "Price: Low to High",
      priceHighLow: "Price: High to Low",
      nameAZ: "Name: A-Z",
      nameZA: "Name: Z-A",
      ratingHigh: "Rating: High",
      clearAllFilters: "Clear All Filters",
      filterToggle: "Filters",
      close: "Close",
      // Error messages
      errorLoadingCategories: "Failed to load categories",
      errorLoadingSubcategories: "Failed to load subcategories",
      // New translations
      subcategories: "Subcategories",
      apply: "Apply",
      searchBrands: "Search Brands",
      noBrandsFound: "No brands found",
      showDiscountedProducts: "Show Discounted Products Only",
      resetFilters: "Reset Filters",
    }, // Product Details
    product: {
      ref: "Ref:",
      reviews: "Reviews",
      dimensions: "Artwork Dimensions",

      deliveryTime: "Delivery Time",
      days: "Days",
      tryInRoom: "Try in Room",
      quantity: "Quantity",
      details: "Description",
      author: "Author",
      similarProducts: "Similar Products",
      selectAgeGroup: "age group",
      selectSize: " size",
      selectColor: " color",
      addToCartSuccess: "Product successfully added to cart!",
      addToCartError: "Failed to add product to cart",
      errorTitle: "Error",
    },

    // Room Viewer
    roomViewer: {
      title: "Try in Room",
      chooseRoom: "Choose Room",
      livingRoom: "Living Room",
      bedroom: "Bedroom",
      kitchen: "Kitchen",
      hall: "Hall",
      artworkSize: "product Size",
      wallColor: "Wall Color",
      instructions:
        "Drag the selected product to the desired position on the wall. Use the size regulator.",
      loading: "Loading room images...",
      artworkLoading: "Loading artwork...",
    },

    // Profile
    profile: {
      title: "User Profile",
      uploadAvatar: "Upload Profile Picture",
      uploading: "Uploading...",
      uploadSuccess: "Image uploaded successfully",
      name: "Name",
      email: "Email",
      newPassword: "New Password",
      confirmPassword: "Confirm New Password",
      passwordPlaceholder: "Leave empty to keep current password",
      updateProfile: "Update Profile",
      updating: "Updating...",
      updateSuccess: "🎉 Profile updated successfully!",
      loading: "Loading...",
      updateError: "Update Error",
      updateErrorDescription:
        "Failed to update profile. Please try again later.",
      uploadError: "Upload Error",
      uploadErrorDescription: "Failed to upload image. Please try again later.",
      passwordChanged: "Password Changed",
      passwordChangedDescription:
        "Your password has been changed successfully.",
      updateSuccessDescription: "Your profile has been updated successfully.",
    },

    // Cart & Checkout
    cart: {
      yourCart: "Your Cart",
      items: "items",
      empty: "Your cart is empty",
      total: "Subtotal",
      viewCart: "View Cart",
      delivery: "Delivery",
      free: "Free",
      commission: "Fee",
      totalCost: "Total",
      checkout: "Checkout",
      remove: "Remove",
      addToCart: "Add to Cart",
      adding: "Adding...",
      outOfStock: "Out of Stock",
      title: "Shopping Cart",
      emptyDescription: "Your cart is empty. Add products to start shopping.",
      size: "Size",
      color: "Color",
      age: "Age",
    },

    // Checkout
    checkout: {
      // Steps
      authenticationStep: "Authentication",
      shippingStep: "Shipping",
      orderStep: "Order",
      // Forms
      shippingAddress: "Shipping Address",
      enterShippingDetails: "Enter your shipping details",
      streetAddress: "Street Address",
      addressPlaceholder: "e.g., 123 Rustaveli Ave",
      addressRequired: "Address is required",
      city: "City",
      cityPlaceholder: "Tbilisi",
      cityRequired: "City is required",
      postalCode: "Postal Code",
      postalCodePlaceholder: "0100",
      postalCodeRequired: "Postal code is required",
      phoneNumber: "Phone Number",
      phoneNumberPlaceholder: "+995 555 123 456",
      phoneNumberRequired: "Phone number is required",
      validPhoneNumber: "Please enter a valid phone number",
      country: "Country",
      selectCountry: "Select a country",
      countryRequired: "Country is required",
      continueToPayment: "Continue to Payment",
      errorSavingShipping: "Error saving shipping details",
      pleaseTryAgain: "Please try again.",
      duplicateOrder: "Order already submitted",
      duplicateOrderDescription: "Please wait or check your orders",
      paymentMethod: "Payment Method",
      choosePaymentMethod: "Choose how you would like to pay",
      cardPayment: "Card Payment",
      continueToReview: "Continue to Review",
      errorSavingPayment: "Error saving payment method",
      shipping: "Shipping",
      address: "Address",
      phone: "Phone",
      payment: "Payment",
      method: "Method",
      orderItems: "Order Items",
      orderSummary: "Order Summary",
      items: "Items",
      shippingCost: "Shipping",
      free: "Free",
      tax: "Tax",
      total: "Total",
      placeOrder: "Place Order",
      placingOrder: "Loading...",
      errorPlacingOrder: "Error placing order",
    },

    // Order Details
    order: {
      order: "Order",
      paid: "Paid",
      pendingPayment: "Pending Payment",
      cancelled: "Cancelled",
      shipping: "Shipping",
      address: "Address",
      phone: "Phone",
      deliveredOn: "Delivered on",
      notDelivered: "Not Delivered",
      payment: "Payment",
      method: "Method",
      paidOn: "Paid on",
      notPaid: "Not Paid",
      orderItems: "Order Items",
      sellerDelivery: "Seller Delivery",
      deliveryTime: "Delivery Time",
      days: "days",
      orderSummary: "Order Summary",
      items: "Items",
      shippingCost: "Shipping",
      free: "Free",
      tax: "Tax",
      total: "Total",
      totalUSD: "Total (USD)",
      stockExpired: "Stock reservation has expired. Please create a new order.",
      orderCancelled: "Order has been cancelled",
      stockReservedUntil: "Stock reserved until",
      paymentButton: "Pay Now",
      processing: "Processing...",
    },

    // About page
    about: {
      title: "About Us",
      description:
        "\u10ea\u10d0\u10db\u10d4\u10e2\u10d8 is a men's classic clothing store in Georgia. Our goal is to offer the highest quality suits, shirts, jackets and accessories for the modern man.",
      mission: {
        title: "Mission",
        description:
          "Our mission is to create a platform for artists where they can share and sell their work, and to provide art lovers with unique artworks.",
      },
      goal: {
        title: "Goal",
        description:
          "Our goal is to unite art lovers and artists in a single space where art is accessible to everyone.",
      },
      vision: {
        title: "Vision",
        description:
          "\u10ea\u10d0\u10db\u10d4\u10e2\u10d8 is a men's classic clothing store that brings elegance and style together. Our vision is to become the primary destination for men's fashion in Georgia.",
      },
      whyUs: {
        title: "Why \u10ea\u10d0\u10db\u10d4\u10e2\u10d8?",
        description:
          "There is no similar platform in Georgia. We create a unique opportunity where art and technology meet.",
      },
      buyUnique: {
        title: "Buy Unique products",
        description:
          "Looking for unique art pieces? Browse our platform and find artwork that matches your taste.",
        button: "Browse products",
      },
    },

    // Footer
    footer: {
      copyright: "CREATED BY",
      description:
        "Explore our playful collection of t-shirts, bags, and accessories with squeaky heart designs that make a fun 'pip' sound when pressed. Add some joy and surprise to your everyday outfits!",
      quickLinks: "Quick Links",
      termsOfService: "Terms of Service",
      privacyPolicy: "Privacy Policy",
      contact: "Contact",
      address: "Address: Tbilisi, Georgia",
      email: "Email: kakhaber.shop13@gmail.com",
      phone: "Phone: +995 574150531",
      socialMedia: "Social Media",
      follow: "Follow us",
      newsletter: "Newsletter",
      subscribePrompt: "Subscribe to our newsletter for updates",
      subscribe: "Subscribe",
      emailPlaceholder: "Enter your email",
      beforeYouLeave: "Before you go, piiip it out!!!",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
      returnPolicy: "Return Policy",
    },

    home: {
      mostPopular: "Most Popular",
      welcomeMessage: "Welcome to Pipiii World !!!",
      pipSound: "Piip Piip!",
    },

    // Timer translations
    timer: {
      loading: "Loading...",
      message: "Time left until website ends",
      day: "Day",
      days: "Days",
      hour: "Hour",
      hours: "Hours",
      minute: "Minute",
      minutes: "Minutes",
      second: "Second",
      seconds: "Seconds",
      month: "Month",
    },

    // Common action buttons
    actions: {
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      delete: "Delete",
      send: "Send",
      create: "Create",
      close: "Close",
      add: "Add",
      back: "Back",
      next: "Next",
      submit: "Submit",
    },

    // Language selector
    language: {
      en: "ENG",
      ge: "GEO",
    },
    auth: {
      login: "Login",
      register: "Register",
      name: "Name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      fullName: "Full Name",
      loginButton: "Login",
      registerButton: "Register",
      alreadyHaveAccount: "Already have an account?",
      dontHaveAccount: "Don't have an account?",
      createAccount: "Create Account",
      loginWelcome: "Sign into your account",
      loginSubtitle: "Welcome back!",
      registerWelcome: "Welcome to Our World!",
      registerSubtitle: "Please fill in the registration form",
      requiredField: "This field is required",
      invalidEmail: "Invalid email address",
      passwordTooShort: "Password must be at least 6 characters",
      passwordsDontMatch: "Passwords don't match",
      termsAgreement: "I agree to the Terms of Service",
      personalInfo: "Personal Information",
      firstName: "First Name",
      lastName: "Last Name",
      phoneNumber: "Phone Number",
      emailRequired: "Email is required",
      enterNewPassword: "Enter new password",
      confirmNewPassword: "Confirm new password",
      registrationSuccessful: "Registration Successful",
      accountCreatedSuccessfully: "Account created successfully",
      redirectingToLogin: "Redirecting to login page",
      loginSuccess: "Login Successful",
      loginFailed: "Login Failed",
      invalidCredentials: "Invalid email or password",
      registrationFailed: "Registration Failed",
      emailAlreadyExists: "This email is already registered",
      invalidData: "Invalid data. Please check your input.",
      orContinueWith: "or continue with",
      forgotPasswordTitle: "Reset Your Password",
      forgotPasswordSubtitle: "Please fill in the password recovery form",
      welcomeBack: "Welcome back!",
      // Validation error messages
      nameRequired: "Name is required",
      nameTooShort: "Name must be at least 3 characters",
      nameInvalid: "Invalid name",
      emailInvalid: "Invalid email address",
      passwordRequired: "Password is required",
      passwordMinLength: "Password must be at least 6 characters",
      agreeToPrivacyPolicy: "I agree to the ",
      privacyPolicy: "Privacy Policy",
      privacyPolicyRequired: "You must accept the privacy policy to register",
      agreeToTermsAndConditions: "I agree to the ",
      termsAndConditions: "Terms and Conditions",
      agreeToReturnPolicy: "I agree to the ",
      returnPolicy: "Return Policy",
      // Forgot/Reset password
      success: "Success",
      error: "Error",
      checkEmailForResetLink: "Check your email for the password reset link",
      somethingWentWrong: "Something went wrong",
      enterYourEmail: "Enter your email address",
      sending: "Sending...",
      sendResetLink: "Send Reset Link",
      invalidResetLink: "Invalid reset link",
      passwordResetSuccessful: "Password reset successful",
      passwordUpdated: "Your password has been updated",
      passwordResetFailed: "Password reset failed",
      newPassword: "New Password",
      updatingPassword: "Updating password...",
      resetPassword: "Reset Password",
      authenticationRequired: "Authentication Required",
      pleaseLogin: "Please log in first",
    },

    // Contact form
    contact: {
      title: "Contact",
      description:
        "If you have questions or would like to get in touch, please fill out the form below.",
      name: "Name",
      email: "Email",
      subject: "Subject",
      message: "Message",
      send: "Send",
      sending: "Sending...",
      nameRequired: "Name is required",
      emailRequired: "Email is required",
      subjectRequired: "Subject is required",
      messageRequired: "Message is required",
      namePlaceholder: "Enter your name",
      emailPlaceholder: "Enter your email",
      subjectPlaceholder: "Enter subject",
      messagePlaceholder: "Enter your message",
      successTitle: "Message Sent!",
      successMessage:
        "Your message has been sent successfully. We will contact you soon!",
      sendAnother: "Send Another Message",
      sendError: "Error sending message. Please try again.",
    },

    // Art Categories
    categories: {
      // Main categories
      paintings: "Paintings",
      handmade: "Handmade",
      clothing: "Clothing",
      accessories: "Accessories",
      footwear: "Footwear",
      swimwear: "Swimwear",

      // Painting subcategories
      oil: "Oil",
      acrylic: "Acrylic",
      watercolor: "Watercolor",
      pastel: "Pastel",
      drawing: "Drawing",
      mixedMedia: "Mixed Media",
      abstract: "Abstract",
      landscape: "Landscape",
      portrait: "Portrait",
      stillLife: "Still Life",
      contemporary: "Contemporary",
      modern: "Modern",
      impressionism: "Impressionism",
      expressionism: "Expressionism",
      realism: "Realism",
      surrealism: "Surrealism",
      digital: "Digital",
      blackAndWhite: "Black & White",
      animation: "Animation",
      digitalIllustrations: "Digital Illustrations",
      other: "Other",

      // Handmade subcategories
      pottery: "Pottery",
      woodwork: "Woodwork",
      jewelry: "Jewelry",
      textile: "Textile",
      glasswork: "Glasswork",
      sculpture: "Sculpture",
      enamel: "Enamel",
      sculptures: "Sculptures",
      otherHandmade: "Other",

      // Clothing subcategories
      tshirts: "T-shirts",
      dresses: "Dresses",
      hoodies: "Hoodies",

      // Accessories subcategories
      caps: "Caps",
      hats: "Hats",

      // Footwear subcategories
      sporty: "Sporty",
      casual: "Casual",

      // Swimwear subcategories
      swimsuits: "Swimsuits",
    },

    // Forum
    forum: {
      addNewPost: "➕ Add new post",
      loadingMore: "Loading more...",
      addPostSeeOthers: "Add post / See other posts",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      reply: "Reply",
      like: "Like",
      unlike: "Unlike",
      writeReply: "Write a reply...",
      writeComment: "Write a comment...",
      posting: "Posting...",
      send: "Send",
      selectTag: "Select a tag",
      creating: "Creating...",
      create: "Create",
      newPost: "Create New Post",
      writePostContent: "Write your post content...",
      tags: {
        handmade: "Handmade Items",
        paintings: "Paintings",
        other: "Other",
      },
    },

    // Categories translations
    productCategories: {
      // Painting subcategories
      პეიზაჟი: "Landscape",
      პორტრეტი: "Portrait",
      აბსტრაქცია: "Abstract",
      "შავ-თეთრი": "Black & White",
      ანიმაციური: "Animation",
      "ციფრული ილუსტრაციები": "Digital Illustrations",
      მინიატურა: "Miniature",
      სხვა: "Other",

      // Handmade subcategories
      კერამიკა: "Pottery",
      "ხის ნაკეთობები": "Woodwork",
      სამკაულები: "Jewelry",
      ტექსტილი: "Textile",
      მინანქარი: "Enamel",
      სკულპტურები: "Sculptures",

      // Clothing subcategories
      მაისურები: "T-shirts",
      კაბები: "Dresses",
      ჰუდები: "Hoodies",

      // Accessories subcategories
      კეპები: "Caps",
      პანამები: "Hats", // Footwear subcategories
      სპორტული: "Sporty",
      ყოველდღიური: "Casual",

      // Swimwear subcategories
      "საცურაო კოსტუმები": "Swimsuits",
    },

    // Admin Orders
    adminOrders: {
      orderNumber: "Order #{id}",
      paid: "Paid",
      cancelled: "Cancelled",
      orderCancelled: "Order has been cancelled. Reason: {reason}",
      "Order has been cancelled": "Order has been cancelled",
      pendingPayment: "Pending Payment",
      markAsDelivered: "Mark as Delivered",
      shipping: "Shipping",
      customer: "Customer",
      address: "Address",
      deliveredOn: "Delivered on {date}",
      notDelivered: "Not Delivered",
      payment: "Payment",
      method: "Method",
      paidOn: "Paid on {date}",
      notPaid: "Not Paid",
      orderItems: "Order Items",
      size: "Size",
      color: "Color",
      age: "Age",
      deliveryTime: "Delivery Time",
      days: "Days",
      orderSummary: "Order Summary",
      items: "Items",
      tax: "Tax",
      total: "Total",
      sellerDelivery: "Ships by Author",
      storeDelivery: "ცამეტი Courier",
      stockReservationExpired:
        "Stock reservation has expired. Please create a new order.",
      stockReservedUntil: "Stock reserved until:",
      print: "Print",
      buyerName: "Buyer Name",
      buyerEmail: "Email",
      orderDate: "Order Date",
      phone: "Phone",
    }, // Admin Products
    adminProducts: {
      products: "Products",
      users: "Users",
      orders: "Orders",
      createUser: "Create User",
      editUser: "Edit User",
      name: "Name",
      email: "Email",
      role: "Role",
      admin: "Admin",
      user: "User",
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
      cancel: "Cancel",
      save: "Save",
      password: "Password",
      confirmPassword: "Confirm Password",
      userCreated: "User created successfully",
      userUpdated: "User updated successfully",
      userDeleted: "User deleted successfully",
      createError: "Failed to create user",
      updateError: "Failed to update user",
      deleteError: "Failed to delete user",
      confirmDeleteUser: "Are you sure you want to delete this user?",
      searchUsers: "Search users...",
      noUsersFound: "No users found",
      totalUsers: "Total Users",
      activeUsers: "Active Users",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
      lastLogin: "Last Login",
      createdAt: "Created At",
      viewDetails: "View Details",
      filterByRole: "Filter by Role",
      allRoles: "All Roles",
      exportUsers: "Export Users",
      importUsers: "Import Users",
      bulkActions: "Bulk Actions",
      selectAll: "Select All",
      selectedUsers: "Selected Users",
      deleteSelected: "Delete Selected",
      activateSelected: "Activate Selected",
      deactivateSelected: "Deactivate Selected",
      // Product form translations
      productName: "Product Name",
      productNameGe: "Product Name (Georgian)",
      productNameEn: "Product Name (English)",
      description: "Description",
      descriptionGe: "Description (Georgian)",
      descriptionEn: "Description (English)",
      price: "Price",
      category: "Category",
      subcategory: "Subcategory",
      selectCategory: "Select Category",
      selectSubcategory: "Select Subcategory",
      ageGroups: "Age Groups",
      sizes: "Sizes",
      colors: "Colors",
      stock: "Stock Quantity",
      brand: "Brand",
      images: "Product Images",
      brandLogo: "Brand Logo (Optional)",
      createProduct: "Create Product",
      updateProduct: "Update Product",
      productCreated: "Product created successfully!",
      productUpdated: "Product updated successfully!",
      loading: "Loading...",
      selectAtLeastOneImage: "Please select at least one image",
      enterBrandName: "Enter brand name",
      productNameEnPlaceholder: "Product name in English (optional)",
      descriptionEnPlaceholder: "Product description in English (optional)",
      // Error messages
      selectCategoryError: "Please select a category",
      selectSubcategoryError: "Please select a subcategory",
      invalidImageFormat: "Only JPG, JPEG and PNG image formats are allowed",
      noImageSelected: "At least one image must be uploaded",
      deliveryDaysRequired:
        "Please specify delivery time if seller handles delivery.",
      authError: "Authorization failed. Please log in again.",
      createUpdateError: "Failed to add/update product",
      generalError: "Something went wrong",
      // Success messages
      productAddedSuccess: "Product added successfully!",
      productUpdatedSuccess: "Product updated successfully!",
      productCreatedToast: "Product Created",
      productUpdatedToast: "Product Updated",
      successTitle: "Success!",
      // Buttons and actions
      removeImage: "✕",
      uploadReminder: "Please select at least one image",
      fixErrorsBeforeSubmit: "Fix errors before submitting",
      requiredFields: "Required fields",
      // Validation error messages
      productNameRequired: "Product name is required",
      productNameInvalid: "Product name is invalid",
      priceRequired: "Price is required",
      priceInvalid: "Price must be a positive number",
      descriptionRequired: "Description is required",
      descriptionInvalid:
        "Description is invalid, must be at least 5 characters",
      brandRequired: "Brand is required",
      brandInvalid: "Brand name is invalid",
    },

    // Admin Categories
    adminCategories: {
      title: "Categories Management",
      categories: "Categories",
      subcategories: "Subcategories",
      add: "Add",
      edit: "Edit",
      delete: "Delete",
      cancel: "Cancel",
      update: "Update",
      confirmDelete: "Are you sure you want to delete this?",
      showInactive: "Show Inactive",
      active: "Active",
      inactive: "Inactive",
      nameGe: "Name (Georgian)",
      nameEn: "Name (English)",
      descriptionGe: "Description (Georgian)",
      descriptionEn: "Description (English)",
      addNewCategory: "Add New Category",
      addNewSubcategory: "Add New Subcategory",
      noCategoriesFound: "No categories found",
      noSubcategoriesFound: "No subcategories found",
      loading: "Loading",
      colors: "Colors",
      sizes: "Sizes",
      ageGroups: "Age Groups",
      attributes: "Attributes",
      confirmDeleteCategory: "Are you sure you want to delete this category?",
      confirmDeleteSubcategory:
        "Are you sure you want to delete this subcategory?",
      createError: "Failed to create subcategory",
      editValue: "Edit",
      newValue: "New Value",
      georgian: "Georgian",
      english: "English",
      enterColor: "Enter color...",
      enterSize: "Enter size...",
      enterAgeGroup: "Enter age group...",
      enterColorEnglish: "Enter color in English...",
      enterAgeGroupEnglish: "Enter age group in English...",
      noDataFound: "No data found",
      updateError: "Failed to update subcategory",
      deleteError: "Failed to delete subcategory",
      retry: "Retry",
    },
    brand: {
      ourPartners: "Our Partners",
      brandSubtitle: "High-quality hunting equipment from leading brands",
    },
  },
};
